### ISSUE TITLE
remove import/no-cycle

### ISSUE THREAD

**Issue by bcomnes** [rainbow-me/eslint-config-rainbow#3]
It slows things down a lot on large projects. 

On the app, its the difference between a 75s lint and a 35s lint. 
On RainbowKit its the difference between a 3 second lint and a 35s lint. 

We can disable it an selectively turn it on in projects, or visaversa. Cycles just aren't a huge issue most of the time.

**Comment by estrattonbailey** [comment]
Fixed in #79 🤗 

We've got a ticket to conditionally enable in in CI too 🔜
